name: "godot-ci"
on:
  push:
    paths-ignore:
      - '**.md'
      - '!ATTRIBUTION.md'
      - '.gitignore'
      - '.gitattributes'

env:
  GODOT_VERSION: 4.2.2
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  test-and-export:
    name: Test and Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Export Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          # 4.2
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          # 4.1
          #ls /root/.local/share/godot/templates/
          #mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Install Plugins Fix Imports
        run: |
          godot --headless --path . -s plug.gd install || true

      - name: Fix Imports
        run: |
          godot --headless --path . --export-pack FixImports /dev/null 2>&1 >/dev/null

      - name: Test
        run: |
          pwd
          godot --headless --path . -s addons/gut/gut_cmdln.gd -gexit

      - name: Export Web
        id: export-web
        env:
          ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: env.ITCHIO_USERNAME && env.ITCHIO_GAME && env.BUTLER_API_KEY
        run: |
          mkdir -v -p exports/web
          godot --headless --path . --export-release "Web" exports/web/index.html

      - name: Cache butler files
        id: cache-butler
        if: steps.export-web.outcome == 'success'
        uses: actions/cache@v4
        with:
          path: butler
          key: ${{ runner.os }}-butler

      - name: Download Butler
        env:
          ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: steps.cache-butler.outputs.cache-hit != 'true' && steps.export-web.outcome == 'success'
        run: |
          wget -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Butler Push
        env:
          ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: env.ITCHIO_USERNAME && env.ITCHIO_GAME && env.BUTLER_API_KEY && steps.export-web.outcome == 'success'
        run: |
          ./butler push exports/web/ ${ITCHIO_USERNAME}/${ITCHIO_GAME}:HTML5
          ./butler status ${ITCHIO_USERNAME}/${ITCHIO_GAME}:HTML5
          ./butler push exports/windows/ ${ITCHIO_USERNAME}/${ITCHIO_GAME}:windows
          ./butler status ${ITCHIO_USERNAME}/${ITCHIO_GAME}:windows
